image: haskell:8.6.3

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

cache:
  paths:
    - .stack
    - .stack-work

stages:
  - build

build:
  stage: build
  script:
    - stack --system-ghc build
