dist: xenial
language: generic
cache:
  directories:
  - "$HOME/.stack"
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc build --only-dependencies
script:
- stack --no-terminal install --flag "rpw:rpw_dist" --local-bin-path "$PWD"
- sha256sum rpw > rpw.sha256.txt
deploy:
  provider: releases
  api_key:
    secure: PvuwLzbX0ezJozcBENZ1g4zkxP9RBaRl9Xk0xAEyuL/Md5+OPTMm6h52QoCcmo+0dx4dTPA28F0r5v1XNPI2hlN6oFi7b+RBoesIZ9EYBkmwTlTMFRSkanIw0F6h9MeTodJXc/6qEOzu9vV114j/dpRtGFsXI6pKzkVV5NKTncIUzzaiN2MkQXm9pUm5RvY8vdzfDK1IIeMgCWalOjNOIS+J+QFlvMBVg/1N+y1BuK4vQfvm/++Ay+9+zku37dp4m6EwB+AYA3ZM7rheMfbbPlvPpUmcPa8PMf/blW1zEQm1f4IBcbinhaiHLxtuKBxL0cO9xesybbCfPk2xqqN2YPU2N2beLyt0qyk95+dtgkrdRrSN06PoLmQ/JVH8tpK/C+n7rHwY4Yp+/4X5YAPu4VvHTPgRYUM2Hx/nVlIW/V1xV4W68cDH5ExnYwDI4LsG6/M0d59Kn9+5QbGbIeFr8pxaQaKFEHz/kwmjLVpEbFJiHMj+ehQmrzUDkCb2A8zcYiWCfiRDSeup/KbhGtK7fQCpkWdGrJFLcV8LYvrRbkJU4aezxxZi3hA+HMzbG0MsVvjbLmW851lTnLKBTaIUJJL60QLgFFPRYjOa7Alx5GkvvDUylfl2hNrrXhWAPO2q/VbS+wlNvRQl0OSOh12+lFKFCOkuSJRVlFLH7mv918A=
  file:
    - rpw
    - rpw.sha256.txt
  skip_cleanup: true
  on:
    repo: thalesmg/rpw
    branch: master
    tags: true
