name:                rpw
version:             0.1.0.0
github:              "thalesmg/rpw"
license:             GPL-3
author:              "Thales Macedo Garitezi"
maintainer:          "thalesmg@gmail.com"
copyright:           "GPLv3"

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis:            "Cache password for sudo and ansible"
category:            Utils

description:         Please see the README on GitHub at <https://github.com/thalesmg/rpw#README.md>

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - regex-posix
  - unix
  - async
  - terminal-size
  - posix-pty

flags:
  rpw_dist:
    manual: true
    default: false

executables:
  rpw:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    when:
      - condition: flag(rpw_dist)
        ld-options: -static
        ghc-options:
          - -O3
          - -fPIC
